import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:confessionapp/src/core/database/app_database.dart';
import 'package:drift/drift.dart';

class DataLoader {
  static Future<List<CommandmentsCompanion>> loadCommandments(
    String languageCode,
  ) async {
    final String jsonString = await rootBundle.loadString(
      'assets/data/commandments/commandments_$languageCode.json',
    );
    final List<dynamic> jsonList = json.decode(jsonString);
    return jsonList.asMap().entries.map((entry) {
      final index = entry.key;
      final json = entry.value;
      return CommandmentsCompanion.insert(
        // id is auto-generated by DB
        commandmentNo: index + 1,
        content: json['content'],
        languageCode: Value(languageCode),
        code: Value(json['code']),
        customTitle: Value(json['custom_title']),
      );
    }).toList();
  }

  static Future<List<ExaminationQuestionsCompanion>> loadQuestions(
    String languageCode,
    List<Commandment> commandments,
  ) async {
    final String jsonString = await rootBundle.loadString(
      'assets/data/questions/questions_$languageCode.json',
    );
    final List<dynamic> jsonList = json.decode(jsonString);
    List<ExaminationQuestionsCompanion> questions = [];

    // Create a map of code -> id for easy lookup
    final Map<String, int> commandmentMap = {};
    for (var c in commandments) {
      if (c.code != null) {
        commandmentMap[c.code!] = c.id;
      }
    }

    for (var item in jsonList) {
      String commandmentCode = item['commandmentCode'];
      int? commandmentId = commandmentMap[commandmentCode];

      if (commandmentId != null) {
        List<dynamic> qList = item['questions'];
        for (var q in qList) {
          questions.add(
            ExaminationQuestionsCompanion.insert(
              commandmentId: commandmentId,
              question: q,
              languageCode: Value(languageCode),
            ),
          );
        }
      }
    }
    return questions;
  }

  static Future<List<FaqsCompanion>> loadFaqs(String languageCode) async {
    try {
      final String jsonString = await rootBundle.loadString(
        'assets/data/faqs/faqs_$languageCode.json',
      );
      final List<dynamic> jsonList = json.decode(jsonString);
      return jsonList.map((json) {
        return FaqsCompanion.insert(
          heading: json['heading'],
          title: json['title'],
          content: json['content'],
          languageCode: Value(languageCode),
        );
      }).toList();
    } catch (e) {
      // Return empty list if file not found (e.g. for Malayalam if not yet added)
      return [];
    }
  }

  static Future<List<QuotesCompanion>> loadQuotes(String languageCode) async {
    try {
      final String jsonString = await rootBundle.loadString(
        'assets/data/quotes/quotes_$languageCode.json',
      );
      final List<dynamic> jsonList = json.decode(jsonString);
      return jsonList.map((json) {
        return QuotesCompanion.insert(
          author: json['author'],
          quote: json['quote'],
          languageCode: Value(languageCode),
        );
      }).toList();
    } catch (e) {
      return [];
    }
  }

  static Future<List<PrayersCompanion>> loadPrayers(String languageCode) async {
    try {
      final String jsonString = await rootBundle.loadString(
        'assets/data/prayers/prayers_$languageCode.json',
      );
      final List<dynamic> jsonList = json.decode(jsonString);
      return jsonList.map((json) {
        return PrayersCompanion.insert(
          title: json['title'],
          content: json['content'],
          displayOrder: json['displayOrder'],
          languageCode: languageCode,
        );
      }).toList();
    } catch (e) {
      return [];
    }
  }
}
